/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * OK response to ContainerCreate operation
 *
 * @param id The ID of the created container
 * @param warnings Warnings encountered when creating the container
 */
@JsonClass(generateAdapter = true)
data class ContainerCreateResponse(
    // The ID of the created container
    @Json(name = "Id")
    var id: kotlin.String,
    // Warnings encountered when creating the container
    @Json(name = "Warnings")
    var warnings: kotlin.collections.MutableList<kotlin.String>? = null,
)
