/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * contains the information returned to a client on the creation of a new service.
 *
 * @param ID The ID of the created service.
 * @param warnings Optional warning message.  FIXME(thaJeztah): this should have \"omitempty\" in the generated type.
 */
@JsonClass(generateAdapter = true)
data class ServiceCreateResponse(
    // The ID of the created service.
    @Json(name = "ID")
    var ID: kotlin.String? = null,
    // Optional warning message.  FIXME(thaJeztah): this should have \"omitempty\" in the generated type.
    @Json(name = "Warnings")
    var warnings: kotlin.collections.MutableList<kotlin.String>? = null,
)
