/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * User modifiable task configuration.
 *
 * @param pluginSpec
 * @param containerSpec
 * @param networkAttachmentSpec
 * @param resources
 * @param restartPolicy
 * @param placement
 * @param forceUpdate A counter that triggers an update even if no relevant parameters have been changed.
 * @param runtime Runtime is the type of runtime specified for the task executor.
 * @param networks Specifies which networks the service should attach to.
 * @param logDriver
 */
@JsonClass(generateAdapter = true)
data class TaskSpec(
    @Json(name = "PluginSpec")
    var pluginSpec: TaskSpecPluginSpec? = null,
    @Json(name = "ContainerSpec")
    var containerSpec: TaskSpecContainerSpec? = null,
    @Json(name = "NetworkAttachmentSpec")
    var networkAttachmentSpec: TaskSpecNetworkAttachmentSpec? = null,
    @Json(name = "Resources")
    var resources: TaskSpecResources? = null,
    @Json(name = "RestartPolicy")
    var restartPolicy: TaskSpecRestartPolicy? = null,
    @Json(name = "Placement")
    var placement: TaskSpecPlacement? = null,
    // A counter that triggers an update even if no relevant parameters have been changed.
    @Json(name = "ForceUpdate")
    var forceUpdate: kotlin.Int? = null,
    // Runtime is the type of runtime specified for the task executor.
    @Json(name = "Runtime")
    var runtime: kotlin.String? = null,
    // Specifies which networks the service should attach to.
    @Json(name = "Networks")
    var networks: kotlin.collections.MutableList<NetworkAttachmentConfig>? = null,
    @Json(name = "LogDriver")
    var logDriver: TaskSpecLogDriver? = null,
)
