/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Volume list response
 *
 * @param volumes List of volumes
 * @param warnings Warnings that occurred when fetching the list of volumes.
 */
@JsonClass(generateAdapter = true)
data class VolumeListResponse(
    // List of volumes
    @Json(name = "Volumes")
    var volumes: kotlin.collections.MutableList<Volume>? = null,
    // Warnings that occurred when fetching the list of volumes.
    @Json(name = "Warnings")
    var warnings: kotlin.collections.MutableList<kotlin.String>? = null,
)
