/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param username
 * @param password
 * @param email Email is an optional value associated with the username.  > **Deprecated**: This field is deprecated since docker 1.11 (API v1.23) and will be removed in a future release.
 * @param serveraddress
 */
@JsonClass(generateAdapter = true)
data class AuthConfig(
    @Json(name = "username")
    var username: kotlin.String? = null,
    @Json(name = "password")
    var password: kotlin.String? = null,
    // Email is an optional value associated with the username.  > **Deprecated**: This field is deprecated since docker 1.11 (API v1.23) and will be removed in a future release.
    @Json(name = "email")
    var email: kotlin.String? = null,
    @Json(name = "serveraddress")
    var serveraddress: kotlin.String? = null,
)
