/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Requirements for the accessible topology of the volume. These fields are optional. For an in-depth description of what these fields mean, see the CSI specification.
 *
 * @param requisite A list of required topologies, at least one of which the volume must be accessible from.
 * @param preferred A list of topologies that the volume should attempt to be provisioned in.
 */
@JsonClass(generateAdapter = true)
data class ClusterVolumeSpecAccessModeAccessibilityRequirements(
    // A list of required topologies, at least one of which the volume must be accessible from.
    @Json(name = "Requisite")
    var requisite: kotlin.collections.MutableList<kotlin.collections.MutableMap<kotlin.String, kotlin.String>>? = null,
    // A list of topologies that the volume should attempt to be provisioned in.
    @Json(name = "Preferred")
    var preferred: kotlin.collections.MutableList<kotlin.collections.MutableMap<kotlin.String, kotlin.String>>? = null,
)
