/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param id The ID of this container
 * @param names The names that this container has been given
 * @param image The name of the image used when creating this container
 * @param imageID The ID of the image that this container was created from
 * @param command Command to run when starting the container
 * @param created When the container was created
 * @param ports The ports exposed by this container
 * @param sizeRw The size of files that have been created or changed by this container
 * @param sizeRootFs The total size of all the files in this container
 * @param labels User-defined key/value metadata.
 * @param state The state of this container (e.g. `Exited`)
 * @param status Additional human-readable status of this container (e.g. `Exit 0`)
 * @param hostConfig
 * @param networkSettings
 * @param mounts
 */
@JsonClass(generateAdapter = true)
data class ContainerSummary(
    // The ID of this container
    @Json(name = "Id")
    var id: kotlin.String? = null,
    // The names that this container has been given
    @Json(name = "Names")
    var names: kotlin.collections.MutableList<kotlin.String>? = null,
    // The name of the image used when creating this container
    @Json(name = "Image")
    var image: kotlin.String? = null,
    // The ID of the image that this container was created from
    @Json(name = "ImageID")
    var imageID: kotlin.String? = null,
    // Command to run when starting the container
    @Json(name = "Command")
    var command: kotlin.String? = null,
    // When the container was created
    @Json(name = "Created")
    var created: kotlin.Long? = null,
    // The ports exposed by this container
    @Json(name = "Ports")
    var ports: kotlin.collections.MutableList<Port>? = null,
    // The size of files that have been created or changed by this container
    @Json(name = "SizeRw")
    var sizeRw: kotlin.Long? = null,
    // The total size of all the files in this container
    @Json(name = "SizeRootFs")
    var sizeRootFs: kotlin.Long? = null,
    // User-defined key/value metadata.
    @Json(name = "Labels")
    var labels: kotlin.collections.MutableMap<kotlin.String, kotlin.String>? = null,
    // The state of this container (e.g. `Exited`)
    @Json(name = "State")
    var state: kotlin.String? = null,
    // Additional human-readable status of this container (e.g. `Exit 0`)
    @Json(name = "Status")
    var status: kotlin.String? = null,
    @Json(name = "HostConfig")
    var hostConfig: ContainerSummaryHostConfig? = null,
    @Json(name = "NetworkSettings")
    var networkSettings: ContainerSummaryNetworkSettings? = null,
    @Json(name = "Mounts")
    var mounts: kotlin.collections.MutableList<MountPoint>? = null,
)
