/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Driver represents a driver (network, logging, secrets).
 *
 * @param name Name of the driver.
 * @param options Key/value map of driver-specific options.
 */
@JsonClass(generateAdapter = true)
data class Driver(
    // Name of the driver.
    @Json(name = "Name")
    var name: kotlin.String,
    // Key/value map of driver-specific options.
    @Json(name = "Options")
    var options: kotlin.collections.MutableMap<kotlin.String, kotlin.String>? = null,
)
