/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import de.gesellix.docker.remote.api.MountVolumeOptionsDriverConfig

/**
 * Optional configuration for the `volume` type.
 *
 * @param noCopy Populate volume with data from the target.
 * @param labels User-defined key/value metadata.
 * @param driverConfig
 */
@JsonClass(generateAdapter = true)
data class MountVolumeOptions(
    // Populate volume with data from the target.
    @Json(name = "NoCopy")
    var noCopy: kotlin.Boolean? = false,
    // User-defined key/value metadata.
    @Json(name = "Labels")
    var labels: kotlin.collections.MutableMap<kotlin.String, kotlin.String>? = null,
    @Json(name = "DriverConfig")
    var driverConfig: MountVolumeOptionsDriverConfig? = null,
)
