/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import de.gesellix.docker.remote.api.PluginDevice

/**
 *
 *
 * @param capabilities
 * @param allowAllDevices
 * @param devices
 */
@JsonClass(generateAdapter = true)
data class PluginConfigLinux(
    @Json(name = "Capabilities")
    var capabilities: kotlin.collections.MutableList<kotlin.String>,
    @Json(name = "AllowAllDevices")
    var allowAllDevices: kotlin.Boolean,
    @Json(name = "Devices")
    var devices: kotlin.collections.MutableList<PluginDevice>,
)
