/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import de.gesellix.docker.remote.api.EndpointPortConfig
import de.gesellix.docker.remote.api.EndpointSpec
import de.gesellix.docker.remote.api.ServiceEndpointVirtualIPsInner

/**
 *
 *
 * @param spec
 * @param ports
 * @param virtualIPs
 */
@JsonClass(generateAdapter = true)
data class ServiceEndpoint(
    @Json(name = "Spec")
    var spec: EndpointSpec? = null,
    @Json(name = "Ports")
    var ports: kotlin.collections.MutableList<EndpointPortConfig>? = null,
    @Json(name = "VirtualIPs")
    var virtualIPs: kotlin.collections.MutableList<ServiceEndpointVirtualIPsInner>? = null,
)
