/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import de.gesellix.docker.remote.api.BuildCache
import de.gesellix.docker.remote.api.ContainerSummary
import de.gesellix.docker.remote.api.ImageSummary
import de.gesellix.docker.remote.api.Volume

/**
 *
 *
 * @param layersSize
 * @param images
 * @param containers
 * @param volumes
 * @param buildCache
 */
@JsonClass(generateAdapter = true)
data class SystemDataUsageResponse(
    @Json(name = "LayersSize")
    var layersSize: kotlin.Long? = null,
    @Json(name = "Images")
    var images: kotlin.collections.MutableList<ImageSummary>? = null,
    @Json(name = "Containers")
    var containers: kotlin.collections.MutableList<ContainerSummary>? = null,
    @Json(name = "Volumes")
    var volumes: kotlin.collections.MutableList<Volume>? = null,
    @Json(name = "BuildCache")
    var buildCache: kotlin.collections.MutableList<BuildCache>? = null,
)
