/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import de.gesellix.docker.remote.api.ContainerStatus
import de.gesellix.docker.remote.api.PortStatus
import de.gesellix.docker.remote.api.TaskState

/**
 * represents the status of a task.
 *
 * @param timestamp
 * @param state
 * @param message
 * @param err
 * @param containerStatus
 * @param portStatus
 */
@JsonClass(generateAdapter = true)
data class TaskStatus(
    @Json(name = "Timestamp")
    var timestamp: kotlin.String? = null,
    @Json(name = "State")
    var state: TaskState? = null,
    @Json(name = "Message")
    var message: kotlin.String? = null,
    @Json(name = "Err")
    var err: kotlin.String? = null,
    @Json(name = "ContainerStatus")
    var containerStatus: ContainerStatus? = null,
    @Json(name = "PortStatus")
    var portStatus: PortStatus? = null,
)
