/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Plugin spec for the service.  *(Experimental release only.)*  <p><br /></p>  > **Note**: ContainerSpec, NetworkAttachmentSpec, and PluginSpec are > mutually exclusive. PluginSpec is only used when the Runtime field > is set to `plugin`. NetworkAttachmentSpec is used when the Runtime > field is set to `attachment`.
 *
 * @param name The name or 'alias' to use for the plugin.
 * @param remote The plugin image reference to use.
 * @param disabled Disable the plugin once scheduled.
 * @param pluginPrivilege
 */
@JsonClass(generateAdapter = true)
data class TaskSpecPluginSpec(
    // The name or 'alias' to use for the plugin.
    @Json(name = "Name")
    var name: kotlin.String? = null,
    // The plugin image reference to use.
    @Json(name = "Remote")
    var remote: kotlin.String? = null,
    // Disable the plugin once scheduled.
    @Json(name = "Disabled")
    var disabled: kotlin.Boolean? = null,
    @Json(name = "PluginPrivilege")
    var pluginPrivilege: kotlin.collections.MutableList<PluginPrivilege>? = null,
)
