/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport"
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Address represents an IPv4 or IPv6 IP address.
 *
 * @param addr IP address.
 * @param prefixLen Mask length of the IP address.
 */
@JsonClass(generateAdapter = true)

data class Address(

  /* IP address. */
  @Json(name = "Addr")
  var addr: kotlin.String? = null,

  /* Mask length of the IP address. */
  @Json(name = "PrefixLen")
  var prefixLen: kotlin.Int? = null

)
