/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport"
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param username
 * @param password
 * @param email
 * @param serveraddress
 */
@JsonClass(generateAdapter = true)

data class AuthConfig(

  @Json(name = "username")
  var username: kotlin.String? = null,

  @Json(name = "password")
  var password: kotlin.String? = null,

  @Json(name = "email")
  var email: kotlin.String? = null,

  @Json(name = "serveraddress")
  var serveraddress: kotlin.String? = null

)
