/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport"
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param ID
 * @param parent
 * @param type
 * @param description
 * @param inUse
 * @param shared
 * @param propertySize Amount of disk space used by the build cache (in bytes).
 * @param createdAt Date and time at which the build cache was created in [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format with nano-seconds.
 * @param lastUsedAt Date and time at which the build cache was last used in [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format with nano-seconds.
 * @param usageCount
 */
@JsonClass(generateAdapter = true)

data class BuildCache(

  @Json(name = "ID")
  var ID: kotlin.String? = null,

  @Json(name = "Parent")
  var parent: kotlin.String? = null,

  @Json(name = "Type")
  var type: kotlin.String? = null,

  @Json(name = "Description")
  var description: kotlin.String? = null,

  @Json(name = "InUse")
  var inUse: kotlin.Boolean? = null,

  @Json(name = "Shared")
  var shared: kotlin.Boolean? = null,

  /* Amount of disk space used by the build cache (in bytes).  */
  @Json(name = "Size")
  var propertySize: kotlin.Int? = null,

  /* Date and time at which the build cache was created in [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format with nano-seconds.  */
  @Json(name = "CreatedAt")
  var createdAt: kotlin.String? = null,

  /* Date and time at which the build cache was last used in [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format with nano-seconds.  */
  @Json(name = "LastUsedAt")
  var lastUsedAt: kotlin.String? = null,

  @Json(name = "UsageCount")
  var usageCount: kotlin.Int? = null

)
