/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param id
 * @param stream
 * @param error
 * @param errorDetail
 * @param status
 * @param progress
 * @param progressDetail
 * @param aux
 */
@JsonClass(generateAdapter = true)
data class BuildInfo(
    @Json(name = "id")
    var id: kotlin.String? = null,
    @Json(name = "stream")
    var stream: kotlin.String? = null,
    @Json(name = "error")
    var error: kotlin.String? = null,
    @Json(name = "errorDetail")
    var errorDetail: ErrorDetail? = null,
    @Json(name = "status")
    var status: kotlin.String? = null,
    @Json(name = "progress")
    var progress: kotlin.String? = null,
    @Json(name = "progressDetail")
    var progressDetail: ProgressDetail? = null,
    @Json(name = "aux")
    var aux: ImageID? = null,
)
