/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * One cluster volume secret entry. Defines a key-value pair that is passed to the plugin.
 *
 * @param key Key is the name of the key of the key-value pair passed to the plugin.
 * @param secret Secret is the swarm Secret object from which to read data. This can be a Secret name or ID. The Secret data is retrieved by swarm and used as the value of the key-value pair passed to the plugin.
 */
@JsonClass(generateAdapter = true)
data class ClusterVolumeSpecAccessModeSecretsInner(
    // Key is the name of the key of the key-value pair passed to the plugin.
    @Json(name = "Key")
    var key: kotlin.String? = null,
    // Secret is the swarm Secret object from which to read data. This can be a Secret name or ID. The Secret data is retrieved by swarm and used as the value of the key-value pair passed to the plugin.
    @Json(name = "Secret")
    var secret: kotlin.String? = null,
)
