/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Options and information specific to, and only present on, Swarm CSI cluster volumes.
 *
 * @param ID The Swarm ID of this volume. Because cluster volumes are Swarm objects, they have an ID, unlike non-cluster volumes. This ID can be used to refer to the Volume instead of the name.
 * @param version
 * @param createdAt
 * @param updatedAt
 * @param spec
 * @param info
 * @param publishStatus The status of the volume as it pertains to its publishing and use on specific nodes
 */
@JsonClass(generateAdapter = true)

data class ClusterVolume(

    /* The Swarm ID of this volume. Because cluster volumes are Swarm objects, they have an ID, unlike non-cluster volumes. This ID can be used to refer to the Volume instead of the name.  */
    @Json(name = "ID")
    var ID: kotlin.String? = null,

    @Json(name = "Version")
    var version: ObjectVersion? = null,

    @Json(name = "CreatedAt")
    var createdAt: kotlin.String? = null,

    @Json(name = "UpdatedAt")
    var updatedAt: kotlin.String? = null,

    @Json(name = "Spec")
    var spec: ClusterVolumeSpec? = null,

    @Json(name = "Info")
    var info: ClusterVolumeInfo? = null,

    /* The status of the volume as it pertains to its publishing and use on specific nodes  */
    @Json(name = "PublishStatus")
    var publishStatus: kotlin.collections.MutableList<ClusterVolumePublishStatusInner>? = null

)
