/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport"
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param id
 * @param error
 * @param status
 * @param progress
 * @param progressDetail
 */
@JsonClass(generateAdapter = true)

data class CreateImageInfo(

  @Json(name = "id")
  var id: kotlin.String? = null,

  @Json(name = "error")
  var error: kotlin.String? = null,

  @Json(name = "status")
  var status: kotlin.String? = null,

  @Json(name = "progress")
  var progress: kotlin.String? = null,

  @Json(name = "progressDetail")
  var progressDetail: ProgressDetail? = null

)
