/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A device mapping between the host and container
 *
 * @param pathOnHost
 * @param pathInContainer
 * @param cgroupPermissions
 */
@JsonClass(generateAdapter = true)

data class DeviceMapping(

    @Json(name = "PathOnHost")
    var pathOnHost: kotlin.String? = null,

    @Json(name = "PathInContainer")
    var pathInContainer: kotlin.String? = null,

    @Json(name = "CgroupPermissions")
    var cgroupPermissions: kotlin.String? = null

)
