/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * EndpointIPAMConfig represents an endpoint's IPAM configuration.
 *
 * @param ipv4Address
 * @param ipv6Address
 * @param linkLocalIPs
 */
@JsonClass(generateAdapter = true)

data class EndpointIPAMConfig(

    @Json(name = "IPv4Address")
    var ipv4Address: kotlin.String? = null,

    @Json(name = "IPv6Address")
    var ipv6Address: kotlin.String? = null,

    @Json(name = "LinkLocalIPs")
    var linkLocalIPs: kotlin.collections.MutableList<kotlin.String>? = null

)
