/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport"
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Properties that can be configured to access and load balance a service.
 *
 * @param mode The mode of resolution to use for internal load balancing between tasks.
 * @param ports List of exposed ports that this service is accessible on from the outside. Ports can only be provided if `vip` resolution mode is used.
 */
@JsonClass(generateAdapter = true)

data class EndpointSpec(

  /* The mode of resolution to use for internal load balancing between tasks.  */
  @Json(name = "Mode")
  var mode: EndpointSpec.Mode? = Mode.Vip,

  /* List of exposed ports that this service is accessible on from the outside. Ports can only be provided if `vip` resolution mode is used.  */
  @Json(name = "Ports")
  var ports: kotlin.collections.MutableList<EndpointPortConfig>? = null

) {

  /**
   * The mode of resolution to use for internal load balancing between tasks.
   *
   * Values: Vip,Dnsrr
   */
  enum class Mode(val value: kotlin.String) {

    @Json(name = "vip")
    Vip("vip"),

    @Json(name = "dnsrr")
    Dnsrr("dnsrr");
  }
}
