/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * EngineDescription provides information about an engine.
 *
 * @param engineVersion
 * @param labels
 * @param plugins
 */
@JsonClass(generateAdapter = true)

data class EngineDescription(

    @Json(name = "EngineVersion")
    var engineVersion: kotlin.String? = null,

    @Json(name = "Labels")
    var labels: kotlin.collections.MutableMap<kotlin.String, kotlin.String>? = null,

    @Json(name = "Plugins")
    var plugins: kotlin.collections.MutableList<EngineDescriptionPluginsInner>? = null

)
