/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Represents an error.
 *
 * @param message The error message.
 */
@JsonClass(generateAdapter = true)

data class ErrorResponse(

    /* The error message. */
    @Json(name = "message")
    var message: kotlin.String

)
