/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport"
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param detach Detach from the command.
 * @param tty Allocate a pseudo-TTY.
 */
@JsonClass(generateAdapter = true)

data class ExecStartConfig(

  /* Detach from the command. */
  @Json(name = "Detach")
  var detach: kotlin.Boolean? = null,

  /* Allocate a pseudo-TTY. */
  @Json(name = "Tty")
  var tty: kotlin.Boolean? = null

)
