/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param namedResourceSpec
 * @param discreteResourceSpec
 */
@JsonClass(generateAdapter = true)

data class GenericResourcesInner(

    @Json(name = "NamedResourceSpec")
    var namedResourceSpec: GenericResourcesInnerNamedResourceSpec? = null,

    @Json(name = "DiscreteResourceSpec")
    var discreteResourceSpec: GenericResourcesInnerDiscreteResourceSpec? = null

)
