/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Information about the storage driver used to store the container's and image's filesystem.
 *
 * @param name Name of the storage driver.
 * @param `data` Low-level storage metadata, provided as key/value pairs.  This information is driver-specific, and depends on the storage-driver in use, and should be used for informational purposes only.
 */
@JsonClass(generateAdapter = true)

data class GraphDriverData(

    /* Name of the storage driver. */
    @Json(name = "Name")
    var name: kotlin.String,

    /* Low-level storage metadata, provided as key/value pairs.  This information is driver-specific, and depends on the storage-driver in use, and should be used for informational purposes only.  */
    @Json(name = "Data")
    var `data`: kotlin.collections.MutableMap<kotlin.String, kotlin.String>? = null

)
