/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport"
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A test to perform to check that the container is healthy.
 *
 * @param test The test to perform. Possible values are:  - `[]` inherit healthcheck from image or parent image - `[\"NONE\"]` disable healthcheck - `[\"CMD\", args...]` exec arguments directly - `[\"CMD-SHELL\", command]` run command with system's default shell
 * @param interval The time to wait between checks in nanoseconds. It should be 0 or at least 1000000 (1 ms). 0 means inherit.
 * @param timeout The time to wait before considering the check to have hung. It should be 0 or at least 1000000 (1 ms). 0 means inherit.
 * @param retries The number of consecutive failures needed to consider a container as unhealthy. 0 means inherit.
 * @param startPeriod Start period for the container to initialize before starting health-retries countdown in nanoseconds. It should be 0 or at least 1000000 (1 ms). 0 means inherit.
 */
@JsonClass(generateAdapter = true)

data class HealthConfig(

  /* The test to perform. Possible values are:  - `[]` inherit healthcheck from image or parent image - `[\"NONE\"]` disable healthcheck - `[\"CMD\", args...]` exec arguments directly - `[\"CMD-SHELL\", command]` run command with system's default shell  */
  @Json(name = "Test")
  var test: kotlin.collections.MutableList<kotlin.String>? = null,

  /* The time to wait between checks in nanoseconds. It should be 0 or at least 1000000 (1 ms). 0 means inherit.  */
  @Json(name = "Interval")
  var interval: kotlin.Long? = null,

  /* The time to wait before considering the check to have hung. It should be 0 or at least 1000000 (1 ms). 0 means inherit.  */
  @Json(name = "Timeout")
  var timeout: kotlin.Long? = null,

  /* The number of consecutive failures needed to consider a container as unhealthy. 0 means inherit.  */
  @Json(name = "Retries")
  var retries: kotlin.Int? = null,

  /* Start period for the container to initialize before starting health-retries countdown in nanoseconds. It should be 0 or at least 1000000 (1 ms). 0 means inherit.  */
  @Json(name = "StartPeriod")
  var startPeriod: kotlin.Long? = null

)
