/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param untagged The image ID of an image that was untagged
 * @param deleted The image ID of an image that was deleted
 */
@JsonClass(generateAdapter = true)

data class ImageDeleteResponseItem(

    /* The image ID of an image that was untagged */
    @Json(name = "Untagged")
    var untagged: kotlin.String? = null,

    /* The image ID of an image that was deleted */
    @Json(name = "Deleted")
    var deleted: kotlin.String? = null

)
