/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport"
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param description
 * @param isOfficial
 * @param isAutomated
 * @param name
 * @param starCount
 */
@JsonClass(generateAdapter = true)

data class ImageSearchResponseItem(

  @Json(name = "description")
  var description: kotlin.String? = null,

  @Json(name = "is_official")
  var isOfficial: kotlin.Boolean? = null,

  @Json(name = "is_automated")
  var isAutomated: kotlin.Boolean? = null,

  @Json(name = "name")
  var name: kotlin.String? = null,

  @Json(name = "star_count")
  var starCount: kotlin.Int? = null

)
