/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param subnet
 * @param ipRange
 * @param gateway
 * @param auxiliaryAddresses
 */
@JsonClass(generateAdapter = true)

data class IPAMConfig(

    @Json(name = "Subnet")
    var subnet: kotlin.String? = null,

    @Json(name = "IPRange")
    var ipRange: kotlin.String? = null,

    @Json(name = "Gateway")
    var gateway: kotlin.String? = null,

    @Json(name = "AuxiliaryAddresses")
    var auxiliaryAddresses: kotlin.collections.MutableMap<kotlin.String, kotlin.String>? = null

)
