/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * An object describing a limit on resources which can be requested by a task.
 *
 * @param nanoCPUs
 * @param memoryBytes
 * @param pids Limits the maximum number of PIDs in the container. Set `0` for unlimited.
 */
@JsonClass(generateAdapter = true)

data class Limit(

    @Json(name = "NanoCPUs")
    var nanoCPUs: kotlin.Long? = null,

    @Json(name = "MemoryBytes")
    var memoryBytes: kotlin.Long? = null,

    /* Limits the maximum number of PIDs in the container. Set `0` for unlimited.  */
    @Json(name = "Pids")
    var pids: kotlin.Long? = 0L

)
