/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param networksDeleted Networks that were deleted
 */
@JsonClass(generateAdapter = true)
data class NetworkPruneResponse(
    // Networks that were deleted
    @Json(name = "NetworksDeleted")
    var networksDeleted: kotlin.collections.MutableList<kotlin.String>? = null,
)
