/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Specifies how a service should be attached to a particular network.
 *
 * @param target The target network for attachment. Must be a network name or ID.
 * @param aliases Discoverable alternate names for the service on this network.
 * @param driverOpts Driver attachment options for the network target.
 */
@JsonClass(generateAdapter = true)

data class NetworkAttachmentConfig(

    /* The target network for attachment. Must be a network name or ID.  */
    @Json(name = "Target")
    var target: kotlin.String? = null,

    /* Discoverable alternate names for the service on this network.  */
    @Json(name = "Aliases")
    var aliases: kotlin.collections.MutableList<kotlin.String>? = null,

    /* Driver attachment options for the network target.  */
    @Json(name = "DriverOpts")
    var driverOpts: kotlin.collections.MutableMap<kotlin.String, kotlin.String>? = null

)
