/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport"
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param id The ID of the created network.
 * @param warning
 */
@JsonClass(generateAdapter = true)

data class NetworkCreateResponse(

  /* The ID of the created network. */
  @Json(name = "Id")
  var id: kotlin.String? = null,

  @Json(name = "Warning")
  var warning: kotlin.String? = null

)
