/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport"
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param name Name for the node.
 * @param labels User-defined key/value metadata.
 * @param role Role of the node.
 * @param availability Availability of the node.
 */
@JsonClass(generateAdapter = true)

data class NodeSpec(

  /* Name for the node. */
  @Json(name = "Name")
  var name: kotlin.String? = null,

  /* User-defined key/value metadata. */
  @Json(name = "Labels")
  var labels: kotlin.collections.MutableMap<kotlin.String, kotlin.String>? = null,

  /* Role of the node. */
  @Json(name = "Role")
  var role: NodeSpec.Role? = null,

  /* Availability of the node. */
  @Json(name = "Availability")
  var availability: NodeSpec.Availability? = null

) {

  /**
   * Role of the node.
   *
   * Values: Worker,Manager
   */
  enum class Role(val value: kotlin.String) {

    @Json(name = "worker")
    Worker("worker"),

    @Json(name = "manager")
    Manager("manager");
  }

  /**
   * Availability of the node.
   *
   * Values: Active,Pause,Drain
   */
  enum class Availability(val value: kotlin.String) {

    @Json(name = "active")
    Active("active"),

    @Json(name = "pause")
    Pause("pause"),

    @Json(name = "drain")
    Drain("drain");
  }
}
