/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A descriptor struct containing digest, media type, and size, as defined in the [OCI Content Descriptors Specification](https://github.com/opencontainers/image-spec/blob/v1.0.1/descriptor.md).
 *
 * @param mediaType The media type of the object this schema refers to.
 * @param digest The digest of the targeted content.
 * @param propertySize The size in bytes of the blob.
 */
@JsonClass(generateAdapter = true)
data class OCIDescriptor(
    // The media type of the object this schema refers to.
    @Json(name = "mediaType")
    var mediaType: kotlin.String? = null,
    // The digest of the targeted content.
    @Json(name = "digest")
    var digest: kotlin.String? = null,
    // The size in bytes of the blob.
    @Json(name = "size")
    var propertySize: kotlin.Long? = null,
)
