/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport"
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Represents a peer-node in the swarm
 *
 * @param nodeID Unique identifier of for this node in the swarm.
 * @param addr IP address and ports at which this node can be reached.
 */
@JsonClass(generateAdapter = true)

data class PeerNode(

  /* Unique identifier of for this node in the swarm. */
  @Json(name = "NodeID")
  var nodeID: kotlin.String? = null,

  /* IP address and ports at which this node can be reached.  */
  @Json(name = "Addr")
  var addr: kotlin.String? = null

)
