/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport"
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The interface between Docker and the plugin
 *
 * @param types
 * @param socket
 * @param protocolScheme Protocol to use for clients connecting to the plugin.
 */
@JsonClass(generateAdapter = true)

data class PluginConfigInterface(

  @Json(name = "Types")
  var types: kotlin.collections.MutableList<PluginInterfaceType>,

  @Json(name = "Socket")
  var socket: kotlin.String,

  /* Protocol to use for clients connecting to the plugin. */
  @Json(name = "ProtocolScheme")
  var protocolScheme: PluginConfigInterface.ProtocolScheme? = null

) {

  /**
   * Protocol to use for clients connecting to the plugin.
   *
   * Values: EMPTY,MobyPeriodPluginsPeriodHttpSlashV1
   */
  @JsonClass(generateAdapter = false)
  enum class ProtocolScheme(val value: kotlin.String) {

    @Json(name = "")
    EMPTY(""),

    @Json(name = "moby.plugins.http/v1")
    MobyPeriodPluginsPeriodHttpSlashV1("moby.plugins.http/v1");
  }
}
