/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport"
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param UID
 * @param GID
 */
@JsonClass(generateAdapter = true)

data class PluginConfigUser(

  @Json(name = "UID")
  var UID: kotlin.Int? = null,

  @Json(name = "GID")
  var GID: kotlin.Int? = null

)
