/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * An object describing the resources which can be advertised by a node and requested by a task.
 *
 * @param nanoCPUs
 * @param memoryBytes
 * @param genericResources User-defined resources can be either Integer resources (e.g, `SSD=3`) or String resources (e.g, `GPU=UUID1`).
 */
@JsonClass(generateAdapter = true)

data class ResourceObject(

    @Json(name = "NanoCPUs")
    var nanoCPUs: kotlin.Long? = null,

    @Json(name = "MemoryBytes")
    var memoryBytes: kotlin.Long? = null,

    /* User-defined resources can be either Integer resources (e.g, `SSD=3`) or String resources (e.g, `GPU=UUID1`).  */
    @Json(name = "GenericResources")
    var genericResources: kotlin.collections.MutableList<GenericResourcesInner>? = null

)
