/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport"
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param path
 * @param weight
 */
@JsonClass(generateAdapter = true)

data class ResourcesBlkioWeightDeviceInner(

  @Json(name = "Path")
  var path: kotlin.String? = null,

  @Json(name = "Weight")
  var weight: kotlin.Int? = null

)
