/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport"
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Runtime describes an [OCI compliant](https://github.com/opencontainers/runtime-spec) runtime.  The runtime is invoked by the daemon via the `containerd` daemon. OCI runtimes act as an interface to the Linux kernel namespaces, cgroups, and SELinux.
 *
 * @param path Name and, optional, path, of the OCI executable binary.  If the path is omitted, the daemon searches the host's `$PATH` for the binary and uses the first result.
 * @param runtimeArgs List of command-line arguments to pass to the runtime when invoked.
 */
@JsonClass(generateAdapter = true)

data class Runtime(

  /* Name and, optional, path, of the OCI executable binary.  If the path is omitted, the daemon searches the host's `$PATH` for the binary and uses the first result.  */
  @Json(name = "path")
  var path: kotlin.String? = null,

  /* List of command-line arguments to pass to the runtime when invoked.  */
  @Json(name = "runtimeArgs")
  var runtimeArgs: kotlin.collections.MutableList<kotlin.String>? = null

)
