/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import de.gesellix.docker.remote.api.ObjectVersion
import de.gesellix.docker.remote.api.SecretSpec

/**
 *
 *
 * @param ID
 * @param version
 * @param createdAt
 * @param updatedAt
 * @param spec
 */
@JsonClass(generateAdapter = true)
data class Secret(
    @Json(name = "ID")
    var ID: kotlin.String? = null,
    @Json(name = "Version")
    var version: ObjectVersion? = null,
    @Json(name = "CreatedAt")
    var createdAt: kotlin.String? = null,
    @Json(name = "UpdatedAt")
    var updatedAt: kotlin.String? = null,
    @Json(name = "Spec")
    var spec: SecretSpec? = null,
)
