/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The mode used for services with a finite number of tasks that run to a completed state.
 *
 * @param maxConcurrent The maximum number of replicas to run simultaneously.
 * @param totalCompletions The total number of replicas desired to reach the Completed state. If unset, will default to the value of `MaxConcurrent`
 */
@JsonClass(generateAdapter = true)

data class ServiceSpecModeReplicatedJob(

    /* The maximum number of replicas to run simultaneously.  */
    @Json(name = "MaxConcurrent")
    var maxConcurrent: kotlin.Long? = 1L,

    /* The total number of replicas desired to reach the Completed state. If unset, will default to the value of `MaxConcurrent`  */
    @Json(name = "TotalCompletions")
    var totalCompletions: kotlin.Long? = null

)
