/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param ID The ID of the created service.
 * @param warning Optional warning message
 */
@JsonClass(generateAdapter = true)

data class ServiceCreateResponse(

    /* The ID of the created service. */
    @Json(name = "ID")
    var ID: kotlin.String? = null,

    /* Optional warning message */
    @Json(name = "Warning")
    var warning: kotlin.String? = null

)
