/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport"
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The status of a service update.
 *
 * @param state
 * @param startedAt
 * @param completedAt
 * @param message
 */
@JsonClass(generateAdapter = true)

data class ServiceUpdateStatus(

  @Json(name = "State")
  var state: ServiceUpdateStatus.State? = null,

  @Json(name = "StartedAt")
  var startedAt: kotlin.String? = null,

  @Json(name = "CompletedAt")
  var completedAt: kotlin.String? = null,

  @Json(name = "Message")
  var message: kotlin.String? = null

) {

  /**
   *
   *
   * Values: Updating,Paused,Completed
   */
  enum class State(val value: kotlin.String) {

    @Json(name = "updating")
    Updating("updating"),

    @Json(name = "paused")
    Paused("paused"),

    @Json(name = "completed")
    Completed("completed");
  }
}
