/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport"
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Scheduling mode for the service.
 *
 * @param replicated
 * @param global
 * @param replicatedJob
 * @param globalJob The mode used for services which run a task to the completed state on each valid node.
 */
@JsonClass(generateAdapter = true)

data class ServiceSpecMode(

  @Json(name = "Replicated")
  var replicated: ServiceSpecModeReplicated? = null,

  @Json(name = "Global")
  var global: kotlin.Any? = null,

  @Json(name = "ReplicatedJob")
  var replicatedJob: ServiceSpecModeReplicatedJob? = null,

  /* The mode used for services which run a task to the completed state on each valid node.  */
  @Json(name = "GlobalJob")
  var globalJob: kotlin.Any? = null

)
