/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The status of the service when it is in one of ReplicatedJob or GlobalJob modes. Absent on Replicated and Global mode services. The JobIteration is an ObjectVersion, but unlike the Service's version, does not need to be sent with an update request.
 *
 * @param jobIteration
 * @param lastExecution The last time, as observed by the server, that this job was started.
 */
@JsonClass(generateAdapter = true)

data class ServiceJobStatus(

    @Json(name = "JobIteration")
    var jobIteration: ObjectVersion? = null,

    /* The last time, as observed by the server, that this job was started.  */
    @Json(name = "LastExecution")
    var lastExecution: kotlin.String? = null

)
