/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param listenAddr Listen address used for inter-manager communication, as well as determining the networking interface used for the VXLAN Tunnel Endpoint (VTEP). This can either be an address/port combination in the form `192.168.1.1:4567`, or an interface followed by a port number, like `eth0:4567`. If the port number is omitted, the default swarm listening port is used.
 * @param advertiseAddr Externally reachable address advertised to other nodes. This can either be an address/port combination in the form `192.168.1.1:4567`, or an interface followed by a port number, like `eth0:4567`. If the port number is omitted, the port number from the listen address is used. If `AdvertiseAddr` is not specified, it will be automatically detected when possible.
 * @param dataPathAddr Address or interface to use for data path traffic (format: `<ip|interface>`), for example,  `192.168.1.1`, or an interface, like `eth0`. If `DataPathAddr` is unspecified, the same address as `AdvertiseAddr` is used.  The `DataPathAddr` specifies the address that global scope network drivers will publish towards other  nodes in order to reach the containers running on this node. Using this parameter it is possible to separate the container data traffic from the management traffic of the cluster.
 * @param dataPathPort DataPathPort specifies the data path port number for data traffic. Acceptable port range is 1024 to 49151. if no port is set or is set to 0, default port 4789 will be used.
 * @param defaultAddrPool Default Address Pool specifies default subnet pools for global scope networks.
 * @param forceNewCluster Force creation of a new swarm.
 * @param subnetSize SubnetSize specifies the subnet size of the networks created from the default subnet pool.
 * @param spec
 */
@JsonClass(generateAdapter = true)

data class SwarmInitRequest(

    /* Listen address used for inter-manager communication, as well as determining the networking interface used for the VXLAN Tunnel Endpoint (VTEP). This can either be an address/port combination in the form `192.168.1.1:4567`, or an interface followed by a port number, like `eth0:4567`. If the port number is omitted, the default swarm listening port is used.  */
    @Json(name = "ListenAddr")
    var listenAddr: kotlin.String? = null,

    /* Externally reachable address advertised to other nodes. This can either be an address/port combination in the form `192.168.1.1:4567`, or an interface followed by a port number, like `eth0:4567`. If the port number is omitted, the port number from the listen address is used. If `AdvertiseAddr` is not specified, it will be automatically detected when possible.  */
    @Json(name = "AdvertiseAddr")
    var advertiseAddr: kotlin.String? = null,

    /* Address or interface to use for data path traffic (format: `<ip|interface>`), for example,  `192.168.1.1`, or an interface, like `eth0`. If `DataPathAddr` is unspecified, the same address as `AdvertiseAddr` is used.  The `DataPathAddr` specifies the address that global scope network drivers will publish towards other  nodes in order to reach the containers running on this node. Using this parameter it is possible to separate the container data traffic from the management traffic of the cluster.  */
    @Json(name = "DataPathAddr")
    var dataPathAddr: kotlin.String? = null,

    /* DataPathPort specifies the data path port number for data traffic. Acceptable port range is 1024 to 49151. if no port is set or is set to 0, default port 4789 will be used.  */
    @Json(name = "DataPathPort")
    var dataPathPort: kotlin.Int? = null,

    /* Default Address Pool specifies default subnet pools for global scope networks.  */
    @Json(name = "DefaultAddrPool")
    var defaultAddrPool: kotlin.collections.MutableList<kotlin.String>? = null,

    /* Force creation of a new swarm. */
    @Json(name = "ForceNewCluster")
    var forceNewCluster: kotlin.Boolean? = null,

    /* SubnetSize specifies the subnet size of the networks created from the default subnet pool.  */
    @Json(name = "SubnetSize")
    var subnetSize: kotlin.Int? = null,

    @Json(name = "Spec")
    var spec: SwarmSpec? = null

)
