/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport"
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Parameters related to encryption-at-rest.
 *
 * @param autoLockManagers If set, generate a key and use it to lock data stored on the managers.
 */
@JsonClass(generateAdapter = true)

data class SwarmSpecEncryptionConfig(

  /* If set, generate a key and use it to lock data stored on the managers.  */
  @Json(name = "AutoLockManagers")
  var autoLockManagers: kotlin.Boolean? = null

)
