/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport"
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * File represents a specific target that is backed by a file.  <p><br /><p>  > **Note**: `Configs.File` and `Configs.Runtime` are mutually exclusive
 *
 * @param name Name represents the final filename in the filesystem.
 * @param UID UID represents the file UID.
 * @param GID GID represents the file GID.
 * @param mode Mode represents the FileMode of the file.
 */
@JsonClass(generateAdapter = true)

data class TaskSpecContainerSpecConfigsInnerFile(

  /* Name represents the final filename in the filesystem.  */
  @Json(name = "Name")
  var name: kotlin.String? = null,

  /* UID represents the file UID. */
  @Json(name = "UID")
  var UID: kotlin.String? = null,

  /* GID represents the file GID. */
  @Json(name = "GID")
  var GID: kotlin.String? = null,

  /* Mode represents the FileMode of the file. */
  @Json(name = "Mode")
  var mode: kotlin.Int? = null

)
