/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param file
 * @param secretID SecretID represents the ID of the specific secret that we're referencing.
 * @param secretName SecretName is the name of the secret that this references, but this is just provided for lookup/display purposes. The secret in the reference will be identified by its ID.
 */
@JsonClass(generateAdapter = true)

data class TaskSpecContainerSpecSecretsInner(

    @Json(name = "File")
    var file: TaskSpecContainerSpecSecretsInnerFile? = null,

    /* SecretID represents the ID of the specific secret that we're referencing.  */
    @Json(name = "SecretID")
    var secretID: kotlin.String? = null,

    /* SecretName is the name of the secret that this references, but this is just provided for lookup/display purposes. The secret in the reference will be identified by its ID.  */
    @Json(name = "SecretName")
    var secretName: kotlin.String? = null

)
