/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Specification for DNS related configurations in resolver configuration file (`resolv.conf`).
 *
 * @param nameservers The IP addresses of the name servers.
 * @param search A search list for host-name lookup.
 * @param options A list of internal resolver variables to be modified (e.g., `debug`, `ndots:3`, etc.).
 */
@JsonClass(generateAdapter = true)
data class TaskSpecContainerSpecDNSConfig(
    // The IP addresses of the name servers.
    @Json(name = "Nameservers")
    var nameservers: kotlin.collections.MutableList<kotlin.String>? = null,
    // A search list for host-name lookup.
    @Json(name = "Search")
    var search: kotlin.collections.MutableList<kotlin.String>? = null,
    // A list of internal resolver variables to be modified (e.g., `debug`, `ndots:3`, etc.).
    @Json(name = "Options")
    var options: kotlin.collections.MutableList<kotlin.String>? = null,
)
