/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport"
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * SELinux labels of the container
 *
 * @param disable Disable SELinux
 * @param user SELinux user label
 * @param role SELinux role label
 * @param type SELinux type label
 * @param level SELinux level label
 */
@JsonClass(generateAdapter = true)

data class TaskSpecContainerSpecPrivilegesSELinuxContext(

  /* Disable SELinux */
  @Json(name = "Disable")
  var disable: kotlin.Boolean? = null,

  /* SELinux user label */
  @Json(name = "User")
  var user: kotlin.String? = null,

  /* SELinux role label */
  @Json(name = "Role")
  var role: kotlin.String? = null,

  /* SELinux type label */
  @Json(name = "Type")
  var type: kotlin.String? = null,

  /* SELinux level label */
  @Json(name = "Level")
  var level: kotlin.String? = null

)
