/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import de.gesellix.docker.remote.api.TaskSpecContainerSpecPrivilegesCredentialSpec
import de.gesellix.docker.remote.api.TaskSpecContainerSpecPrivilegesSELinuxContext

/**
 * Security options for the container
 *
 * @param credentialSpec
 * @param seLinuxContext
 */
@JsonClass(generateAdapter = true)
data class TaskSpecContainerSpecPrivileges(
    @Json(name = "CredentialSpec")
    var credentialSpec: TaskSpecContainerSpecPrivilegesCredentialSpec? = null,
    @Json(name = "SELinuxContext")
    var seLinuxContext: TaskSpecContainerSpecPrivilegesSELinuxContext? = null,
)
