/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * represents system data usage for build cache resources.
 *
 * @param activeCount Count of active build cache records.
 * @param totalCount Count of all build cache records.
 * @param reclaimable Disk space that can be reclaimed by removing inactive build cache records.
 * @param totalSize Disk space in use by build cache records.
 * @param items List of build cache records.
 */
@JsonClass(generateAdapter = true)
data class BuildCacheDiskUsage(
    // Count of active build cache records.
    @Json(name = "ActiveCount")
    var activeCount: kotlin.Long? = null,
    // Count of all build cache records.
    @Json(name = "TotalCount")
    var totalCount: kotlin.Long? = null,
    // Disk space that can be reclaimed by removing inactive build cache records.
    @Json(name = "Reclaimable")
    var reclaimable: kotlin.Long? = null,
    // Disk space in use by build cache records.
    @Json(name = "TotalSize")
    var totalSize: kotlin.Long? = null,
    // List of build cache records.
    @Json(name = "Items")
    var items: kotlin.collections.MutableList<kotlin.Any>? = null,
)
