/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Summary of host-specific runtime information of the container. This is a reduced set of information in the container's \"HostConfig\" as available in the container \"inspect\" response.
 *
 * @param networkMode Networking mode (`host`, `none`, `container:<id>`) or name of the primary network the container is using.  This field is primarily for backward compatibility. The container can be connected to multiple networks for which information can be found in the `NetworkSettings.Networks` field, which enumerates settings per network.
 * @param annotations Arbitrary key-value metadata attached to the container.
 */
@JsonClass(generateAdapter = true)
data class ContainerSummaryHostConfig(
    // Networking mode (`host`, `none`, `container:<id>`) or name of the primary network the container is using.  This field is primarily for backward compatibility. The container can be connected to multiple networks for which information can be found in the `NetworkSettings.Networks` field, which enumerates settings per network.
    @Json(name = "NetworkMode")
    var networkMode: kotlin.String? = null,
    // Arbitrary key-value metadata attached to the container.
    @Json(name = "Annotations")
    var annotations: kotlin.collections.MutableMap<kotlin.String, kotlin.String>? = null,
)
