/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Aggregates all memory stats since container inception on Linux. Windows returns stats for commit and private working set only.
 *
 * @param usage Current `res_counter` usage for memory.  This field is Linux-specific and omitted for Windows containers.
 * @param maxUsage Maximum usage ever recorded.  This field is Linux-specific and only supported on cgroups v1. It is omitted when using cgroups v2 and for Windows containers.
 * @param stats All the stats exported via memory.stat. when using cgroups v2.  This field is Linux-specific and omitted for Windows containers.
 * @param failcnt Number of times memory usage hits limits.  This field is Linux-specific and only supported on cgroups v1. It is omitted when using cgroups v2 and for Windows containers.
 * @param limit This field is Linux-specific and omitted for Windows containers.
 * @param commitbytes Committed bytes.  This field is Windows-specific and omitted for Linux containers.
 * @param commitpeakbytes Peak committed bytes.  This field is Windows-specific and omitted for Linux containers.
 * @param privateworkingset Private working set.  This field is Windows-specific and omitted for Linux containers.
 */
@JsonClass(generateAdapter = true)
data class ContainerMemoryStats(
    // Current `res_counter` usage for memory.  This field is Linux-specific and omitted for Windows containers.
    @Json(name = "usage")
    var usage: kotlin.Int? = null,
    // Maximum usage ever recorded.  This field is Linux-specific and only supported on cgroups v1. It is omitted when using cgroups v2 and for Windows containers.
    @Json(name = "max_usage")
    var maxUsage: kotlin.Int? = null,
    // All the stats exported via memory.stat. when using cgroups v2.  This field is Linux-specific and omitted for Windows containers.
    @Json(name = "stats")
    var stats: kotlin.collections.MutableMap<kotlin.String, kotlin.Int>? = null,
    // Number of times memory usage hits limits.  This field is Linux-specific and only supported on cgroups v1. It is omitted when using cgroups v2 and for Windows containers.
    @Json(name = "failcnt")
    var failcnt: kotlin.Int? = null,
    // This field is Linux-specific and omitted for Windows containers.
    @Json(name = "limit")
    var limit: kotlin.Int? = null,
    // Committed bytes.  This field is Windows-specific and omitted for Linux containers.
    @Json(name = "commitbytes")
    var commitbytes: kotlin.Int? = null,
    // Peak committed bytes.  This field is Windows-specific and omitted for Linux containers.
    @Json(name = "commitpeakbytes")
    var commitpeakbytes: kotlin.Int? = null,
    // Private working set.  This field is Windows-specific and omitted for Linux containers.
    @Json(name = "privateworkingset")
    var privateworkingset: kotlin.Int? = null,
)
