/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import de.gesellix.docker.remote.api.ContainerdInfoNamespaces

/**
 * Information for connecting to the containerd instance that is used by the daemon. This is included for debugging purposes only.
 *
 * @param address The address of the containerd socket.
 * @param namespaces
 */
@JsonClass(generateAdapter = true)
data class ContainerdInfo(
    // The address of the containerd socket.
    @Json(name = "Address")
    var address: kotlin.String? = null,
    @Json(name = "Namespaces")
    var namespaces: ContainerdInfoNamespaces? = null,
)
