/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * PidsStats contains Linux-specific stats of a container's process-IDs (PIDs).  This type is Linux-specific and omitted for Windows containers.
 *
 * @param current Current is the number of PIDs in the cgroup.
 * @param limit Limit is the hard limit on the number of pids in the cgroup. A \"Limit\" of 0 means that there is no limit.
 */
@JsonClass(generateAdapter = true)
data class ContainerPidsStats(
    // Current is the number of PIDs in the cgroup.
    @Json(name = "current")
    var current: kotlin.Int? = null,
    // Limit is the hard limit on the number of pids in the cgroup. A \"Limit\" of 0 means that there is no limit.
    @Json(name = "limit")
    var limit: kotlin.Int? = null,
)
