/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Blkio stats entry.  This type is Linux-specific and omitted for Windows containers.
 *
 * @param major
 * @param minor
 * @param op
 * @param `value`
 */
@JsonClass(generateAdapter = true)
data class ContainerBlkioStatEntry(
    @Json(name = "major")
    var major: kotlin.Int? = null,
    @Json(name = "minor")
    var minor: kotlin.Int? = null,
    @Json(name = "op")
    var op: kotlin.String? = null,
    @Json(name = "value")
    var `value`: kotlin.Int? = null,
)
