/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Summary of health status  Added in v1.52, before that version all container summary not include Health. After this attribute introduced, it includes containers with no health checks configured, or containers that are not running with none
 *
 * @param status the health status of the container
 * @param failingStreak FailingStreak is the number of consecutive failures
 */
@JsonClass(generateAdapter = true)
data class ContainerSummaryHealth(
    // the health status of the container
    @Json(name = "Status")
    var status: ContainerSummaryHealth.Status? = null,
    // FailingStreak is the number of consecutive failures
    @Json(name = "FailingStreak")
    var failingStreak: kotlin.Int? = null,
) {
    /**
     * the health status of the container
     *
     * Values: None,Starting,Healthy,Unhealthy
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "none")
        None("none"),

        @Json(name = "starting")
        Starting("starting"),

        @Json(name = "healthy")
        Healthy("healthy"),

        @Json(name = "unhealthy")
        Unhealthy("unhealthy"),
    }
}
