/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Summary of the container's network settings
 *
 * @param networks Summary of network-settings for each network the container is attached to.
 */
@JsonClass(generateAdapter = true)
data class ContainerSummaryNetworkSettings(
    // Summary of network-settings for each network the container is attached to.
    @Json(name = "Networks")
    var networks: kotlin.collections.MutableMap<kotlin.String, EndpointSettings>? = null,
)
