/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Aggregates the network stats of one container
 *
 * @param rxBytes Bytes received. Windows and Linux.
 * @param rxPackets Packets received. Windows and Linux.
 * @param rxErrors Received errors. Not used on Windows.  This field is Linux-specific and always zero for Windows containers.
 * @param rxDropped Incoming packets dropped. Windows and Linux.
 * @param txBytes Bytes sent. Windows and Linux.
 * @param txPackets Packets sent. Windows and Linux.
 * @param txErrors Sent errors. Not used on Windows.  This field is Linux-specific and always zero for Windows containers.
 * @param txDropped Outgoing packets dropped. Windows and Linux.
 * @param endpointId Endpoint ID. Not used on Linux.  This field is Windows-specific and omitted for Linux containers.
 * @param instanceId Instance ID. Not used on Linux.  This field is Windows-specific and omitted for Linux containers.
 */
@JsonClass(generateAdapter = true)
data class ContainerNetworkStats(
    // Bytes received. Windows and Linux.
    @Json(name = "rx_bytes")
    var rxBytes: kotlin.Int? = null,
    // Packets received. Windows and Linux.
    @Json(name = "rx_packets")
    var rxPackets: kotlin.Int? = null,
    // Received errors. Not used on Windows.  This field is Linux-specific and always zero for Windows containers.
    @Json(name = "rx_errors")
    var rxErrors: kotlin.Int? = null,
    // Incoming packets dropped. Windows and Linux.
    @Json(name = "rx_dropped")
    var rxDropped: kotlin.Int? = null,
    // Bytes sent. Windows and Linux.
    @Json(name = "tx_bytes")
    var txBytes: kotlin.Int? = null,
    // Packets sent. Windows and Linux.
    @Json(name = "tx_packets")
    var txPackets: kotlin.Int? = null,
    // Sent errors. Not used on Windows.  This field is Linux-specific and always zero for Windows containers.
    @Json(name = "tx_errors")
    var txErrors: kotlin.Int? = null,
    // Outgoing packets dropped. Windows and Linux.
    @Json(name = "tx_dropped")
    var txDropped: kotlin.Int? = null,
    // Endpoint ID. Not used on Linux.  This field is Windows-specific and omitted for Linux containers.
    @Json(name = "endpoint_id")
    var endpointId: kotlin.String? = null,
    // Instance ID. Not used on Linux.  This field is Windows-specific and omitted for Linux containers.
    @Json(name = "instance_id")
    var instanceId: kotlin.String? = null,
)
