/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Response for a successful container-update.
 *
 * @param warnings Warnings encountered when updating the container.
 */
@JsonClass(generateAdapter = true)
data class ContainerUpdateResponse(
    // Warnings encountered when updating the container.
    @Json(name = "Warnings")
    var warnings: kotlin.collections.MutableList<kotlin.String>? = null,
)
