/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * All CPU stats aggregated since container inception.
 *
 * @param totalUsage Total CPU time consumed in nanoseconds (Linux) or 100's of nanoseconds (Windows).
 * @param percpuUsage Total CPU time (in nanoseconds) consumed per core (Linux).  This field is Linux-specific when using cgroups v1. It is omitted when using cgroups v2 and Windows containers.
 * @param usageInKernelmode Time (in nanoseconds) spent by tasks of the cgroup in kernel mode (Linux), or time spent (in 100's of nanoseconds) by all container processes in kernel mode (Windows).  Not populated for Windows containers using Hyper-V isolation.
 * @param usageInUsermode Time (in nanoseconds) spent by tasks of the cgroup in user mode (Linux), or time spent (in 100's of nanoseconds) by all container processes in kernel mode (Windows).  Not populated for Windows containers using Hyper-V isolation.
 */
@JsonClass(generateAdapter = true)
data class ContainerCPUUsage(
    // Total CPU time consumed in nanoseconds (Linux) or 100's of nanoseconds (Windows).
    @Json(name = "total_usage")
    var totalUsage: kotlin.Int? = null,
    // Total CPU time (in nanoseconds) consumed per core (Linux).  This field is Linux-specific when using cgroups v1. It is omitted when using cgroups v2 and Windows containers.
    @Json(name = "percpu_usage")
    var percpuUsage: kotlin.collections.MutableList<kotlin.Int>? = null,
    // Time (in nanoseconds) spent by tasks of the cgroup in kernel mode (Linux), or time spent (in 100's of nanoseconds) by all container processes in kernel mode (Windows).  Not populated for Windows containers using Hyper-V isolation.
    @Json(name = "usage_in_kernelmode")
    var usageInKernelmode: kotlin.Int? = null,
    // Time (in nanoseconds) spent by tasks of the cgroup in user mode (Linux), or time spent (in 100's of nanoseconds) by all container processes in kernel mode (Windows).  Not populated for Windows containers using Hyper-V isolation.
    @Json(name = "usage_in_usermode")
    var usageInUsermode: kotlin.Int? = null,
)
