/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param id The ID of this container as a 128-bit (64-character) hexadecimal string (32 bytes).
 * @param names The names associated with this container. Most containers have a single name, but when using legacy \"links\", the container can have multiple names.  For historic reasons, names are prefixed with a forward-slash (`/`).
 * @param image The name or ID of the image used to create the container.  This field shows the image reference as was specified when creating the container, which can be in its canonical form (e.g., `docker.io/library/ubuntu:latest` or `docker.io/library/ubuntu@sha256:72297848456d5d37d1262630108ab308d3e9ec7ed1c3286a32fe09856619a782`), short form (e.g., `ubuntu:latest`)), or the ID(-prefix) of the image (e.g., `72297848456d`).  The content of this field can be updated at runtime if the image used to create the container is untagged, in which case the field is updated to contain the the image ID (digest) it was resolved to in its canonical, non-truncated form (e.g., `sha256:72297848456d5d37d1262630108ab308d3e9ec7ed1c3286a32fe09856619a782`).
 * @param imageID The ID (digest) of the image that this container was created from.
 * @param imageManifestDescriptor
 * @param command Command to run when starting the container
 * @param created Date and time at which the container was created as a Unix timestamp (number of seconds since EPOCH).
 * @param ports Port-mappings for the container.
 * @param sizeRw The size of files that have been created or changed by this container.  This field is omitted by default, and only set when size is requested in the API request.
 * @param sizeRootFs The total size of all files in the read-only layers from the image that the container uses. These layers can be shared between containers.  This field is omitted by default, and only set when size is requested in the API request.
 * @param labels User-defined key/value metadata.
 * @param state The state of this container.
 * @param status Additional human-readable status of this container (e.g. `Exit 0`)
 * @param hostConfig
 * @param networkSettings
 * @param mounts List of mounts used by the container.
 * @param health
 */
@JsonClass(generateAdapter = true)
data class ContainerSummary(
    // The ID of this container as a 128-bit (64-character) hexadecimal string (32 bytes).
    @Json(name = "Id")
    var id: kotlin.String? = null,
    // The names associated with this container. Most containers have a single name, but when using legacy \"links\", the container can have multiple names.  For historic reasons, names are prefixed with a forward-slash (`/`).
    @Json(name = "Names")
    var names: kotlin.collections.MutableList<kotlin.String>? = null,
    // The name or ID of the image used to create the container.  This field shows the image reference as was specified when creating the container, which can be in its canonical form (e.g., `docker.io/library/ubuntu:latest` or `docker.io/library/ubuntu@sha256:72297848456d5d37d1262630108ab308d3e9ec7ed1c3286a32fe09856619a782`), short form (e.g., `ubuntu:latest`)), or the ID(-prefix) of the image (e.g., `72297848456d`).  The content of this field can be updated at runtime if the image used to create the container is untagged, in which case the field is updated to contain the the image ID (digest) it was resolved to in its canonical, non-truncated form (e.g., `sha256:72297848456d5d37d1262630108ab308d3e9ec7ed1c3286a32fe09856619a782`).
    @Json(name = "Image")
    var image: kotlin.String? = null,
    // The ID (digest) of the image that this container was created from.
    @Json(name = "ImageID")
    var imageID: kotlin.String? = null,
    @Json(name = "ImageManifestDescriptor")
    var imageManifestDescriptor: OCIDescriptor? = null,
    // Command to run when starting the container
    @Json(name = "Command")
    var command: kotlin.String? = null,
    // Date and time at which the container was created as a Unix timestamp (number of seconds since EPOCH).
    @Json(name = "Created")
    var created: kotlin.Long? = null,
    // Port-mappings for the container.
    @Json(name = "Ports")
    var ports: kotlin.collections.MutableList<PortSummary>? = null,
    // The size of files that have been created or changed by this container.  This field is omitted by default, and only set when size is requested in the API request.
    @Json(name = "SizeRw")
    var sizeRw: kotlin.Long? = null,
    // The total size of all files in the read-only layers from the image that the container uses. These layers can be shared between containers.  This field is omitted by default, and only set when size is requested in the API request.
    @Json(name = "SizeRootFs")
    var sizeRootFs: kotlin.Long? = null,
    // User-defined key/value metadata.
    @Json(name = "Labels")
    var labels: kotlin.collections.MutableMap<kotlin.String, kotlin.String>? = null,
    // The state of this container.
    @Json(name = "State")
    var state: ContainerSummary.State? = null,
    // Additional human-readable status of this container (e.g. `Exit 0`)
    @Json(name = "Status")
    var status: kotlin.String? = null,
    @Json(name = "HostConfig")
    var hostConfig: ContainerSummaryHostConfig? = null,
    @Json(name = "NetworkSettings")
    var networkSettings: ContainerSummaryNetworkSettings? = null,
    // List of mounts used by the container.
    @Json(name = "Mounts")
    var mounts: kotlin.collections.MutableList<MountPoint>? = null,
    @Json(name = "Health")
    var health: ContainerSummaryHealth? = null,
) {
    /**
     * The state of this container.
     *
     * Values: Created,Running,Paused,Restarting,Exited,Removing,Dead
     */
    @JsonClass(generateAdapter = false)
    enum class State(val value: kotlin.String) {
        @Json(name = "created")
        Created("created"),

        @Json(name = "running")
        Running("running"),

        @Json(name = "paused")
        Paused("paused"),

        @Json(name = "restarting")
        Restarting("restarting"),

        @Json(name = "exited")
        Exited("exited"),

        @Json(name = "removing")
        Removing("removing"),

        @Json(name = "dead")
        Dead("dead"),
    }
}
