/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A request for devices to be sent to device drivers
 *
 * @param driver The name of the device driver to use for this request.  Note that if this is specified the capabilities are ignored when selecting a device driver.
 * @param count
 * @param deviceIDs
 * @param capabilities A list of capabilities; an OR list of AND lists of capabilities.  Note that if a driver is specified the capabilities have no effect on selecting a driver as the driver name is used directly.  Note that if no driver is specified the capabilities are used to select a driver with the required capabilities.
 * @param options Driver-specific options, specified as a key/value pairs. These options are passed directly to the driver.
 */
@JsonClass(generateAdapter = true)
data class DeviceRequest(
    // The name of the device driver to use for this request.  Note that if this is specified the capabilities are ignored when selecting a device driver.
    @Json(name = "Driver")
    var driver: kotlin.String? = null,
    @Json(name = "Count")
    var count: kotlin.Int? = null,
    @Json(name = "DeviceIDs")
    var deviceIDs: kotlin.collections.MutableList<kotlin.String>? = null,
    // A list of capabilities; an OR list of AND lists of capabilities.  Note that if a driver is specified the capabilities have no effect on selecting a driver as the driver name is used directly.  Note that if no driver is specified the capabilities are used to select a driver with the required capabilities.
    @Json(name = "Capabilities")
    var capabilities: kotlin.collections.MutableList<kotlin.collections.MutableList<kotlin.String>>? = null,
    // Driver-specific options, specified as a key/value pairs. These options are passed directly to the driver.
    @Json(name = "Options")
    var options: kotlin.collections.MutableMap<kotlin.String, kotlin.String>? = null,
)
