/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * DeviceInfo represents a device that can be used by a container.
 *
 * @param source The origin device driver.
 * @param ID The unique identifier for the device within its source driver. For CDI devices, this would be an FQDN like \"vendor.com/gpu=0\".
 */
@JsonClass(generateAdapter = true)
data class DeviceInfo(
    // The origin device driver.
    @Json(name = "Source")
    var source: kotlin.String? = null,
    // The unique identifier for the device within its source driver. For CDI devices, this would be an FQDN like \"vendor.com/gpu=0\".
    @Json(name = "ID")
    var ID: kotlin.String? = null,
)
