/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The logging configuration for this container
 *
 * @param type Name of the logging driver used for the container or \"none\" if logging is disabled.
 * @param config Driver-specific configuration options for the logging driver.
 */
@JsonClass(generateAdapter = true)
data class HostConfigAllOfLogConfig(
    // Name of the logging driver used for the container or \"none\" if logging is disabled.
    @Json(name = "Type")
    var type: HostConfigAllOfLogConfig.Type? = null,
    // Driver-specific configuration options for the logging driver.
    @Json(name = "Config")
    var config: kotlin.collections.MutableMap<kotlin.String, kotlin.String>? = null,
) {
    /**
     * Name of the logging driver used for the container or \"none\" if logging is disabled.
     *
     * Values: Local,JsonFile,Syslog,Journald,Gelf,Fluentd,Awslogs,Splunk,Etwlogs,None
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "local")
        Local("local"),

        @Json(name = "json-file")
        JsonFile("json-file"),

        @Json(name = "syslog")
        Syslog("syslog"),

        @Json(name = "journald")
        Journald("journald"),

        @Json(name = "gelf")
        Gelf("gelf"),

        @Json(name = "fluentd")
        Fluentd("fluentd"),

        @Json(name = "awslogs")
        Awslogs("awslogs"),

        @Json(name = "splunk")
        Splunk("splunk"),

        @Json(name = "etwlogs")
        Etwlogs("etwlogs"),

        @Json(name = "none")
        None("none"),
    }
}
