/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The image data for the image manifest. This field is only populated when Kind is \"image\".
 *
 * @param platform
 * @param containers The IDs of the containers that are using this image.
 * @param propertySize
 */
@JsonClass(generateAdapter = true)
data class ImageManifestSummaryImageData(
    @Json(name = "Platform")
    var platform: OCIPlatform?,
    // The IDs of the containers that are using this image.
    @Json(name = "Containers")
    var containers: kotlin.collections.MutableList<kotlin.String>,
    @Json(name = "Size")
    var propertySize: ImageManifestSummaryImageDataSize,
)
