/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The image data for the attestation manifest. This field is only populated when Kind is \"attestation\".
 *
 * @param `for` The digest of the image manifest that this attestation is for.
 */
@JsonClass(generateAdapter = true)
data class ImageManifestSummaryAttestationData(
    // The digest of the image manifest that this attestation is for.
    @Json(name = "For")
    var `for`: kotlin.String,
)
