/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * ImageManifestSummary represents a summary of an image manifest.
 *
 * @param ID ID is the content-addressable ID of an image and is the same as the digest of the image manifest.
 * @param descriptor
 * @param available Indicates whether all the child content (image config, layers) is fully available locally.
 * @param propertySize
 * @param kind The kind of the manifest.  kind         | description -------------|----------------------------------------------------------- image        | Image manifest that can be used to start a container. attestation  | Attestation manifest produced by the Buildkit builder for a specific image manifest.
 * @param imageData
 * @param attestationData
 */
@JsonClass(generateAdapter = true)
data class ImageManifestSummary(
    // ID is the content-addressable ID of an image and is the same as the digest of the image manifest.
    @Json(name = "ID")
    var ID: kotlin.String,
    @Json(name = "Descriptor")
    var descriptor: OCIDescriptor,
    // Indicates whether all the child content (image config, layers) is fully available locally.
    @Json(name = "Available")
    var available: kotlin.Boolean,
    @Json(name = "Size")
    var propertySize: ImageManifestSummarySize,
    // The kind of the manifest.  kind         | description -------------|----------------------------------------------------------- image        | Image manifest that can be used to start a container. attestation  | Attestation manifest produced by the Buildkit builder for a specific image manifest.
    @Json(name = "Kind")
    var kind: ImageManifestSummary.Kind,
    @Json(name = "ImageData")
    var imageData: ImageManifestSummaryImageData? = null,
    @Json(name = "AttestationData")
    var attestationData: ImageManifestSummaryAttestationData? = null,
) {
    /**
     * The kind of the manifest.  kind         | description -------------|----------------------------------------------------------- image        | Image manifest that can be used to start a container. attestation  | Attestation manifest produced by the Buildkit builder for a specific image manifest.
     *
     * Values: Image,Attestation,Unknown
     */
    @JsonClass(generateAdapter = false)
    enum class Kind(val value: kotlin.String) {
        @Json(name = "image")
        Image("image"),

        @Json(name = "attestation")
        Attestation("attestation"),

        @Json(name = "unknown")
        Unknown("unknown"),
    }
}
