/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param subnets
 */
@JsonClass(generateAdapter = true)
data class IPAMStatus(
    @Json(name = "Subnets")
    var subnets: kotlin.collections.MutableMap<kotlin.String, SubnetStatus>? = null,
)
