/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * NetworkSettings exposes the network settings in the API
 *
 * @param sandboxID SandboxID uniquely represents a container's network stack.
 * @param sandboxKey SandboxKey is the full path of the netns handle
 * @param ports PortMap describes the mapping of container ports to host ports, using the container's port-number and protocol as key in the format `<port>/<protocol>`, for example, `80/udp`.  If a container's port is mapped for multiple protocols, separate entries are added to the mapping table.
 * @param networks Information about all networks that the container is connected to.
 */
@JsonClass(generateAdapter = true)
data class NetworkSettings(
    // SandboxID uniquely represents a container's network stack.
    @Json(name = "SandboxID")
    var sandboxID: kotlin.String? = null,
    // SandboxKey is the full path of the netns handle
    @Json(name = "SandboxKey")
    var sandboxKey: kotlin.String? = null,
    // PortMap describes the mapping of container ports to host ports, using the container's port-number and protocol as key in the format `<port>/<protocol>`, for example, `80/udp`.  If a container's port is mapped for multiple protocols, separate entries are added to the mapping table.
    @Json(name = "Ports")
    var ports: kotlin.collections.MutableMap<kotlin.String, kotlin.collections.MutableList<PortBinding>>? = null,
    // Information about all networks that the container is connected to.
    @Json(name = "Networks")
    var networks: kotlin.collections.MutableMap<kotlin.String, EndpointSettings>? = null,
)
