/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * carries the information about one backend task
 *
 * @param name
 * @param endpointID
 * @param endpointIP
 * @param info
 */
@JsonClass(generateAdapter = true)
data class NetworkTaskInfo(
    @Json(name = "Name")
    var name: kotlin.String? = null,
    @Json(name = "EndpointID")
    var endpointID: kotlin.String? = null,
    @Json(name = "EndpointIP")
    var endpointIP: kotlin.String? = null,
    @Json(name = "Info")
    var info: kotlin.collections.MutableMap<kotlin.String, kotlin.String>? = null,
)
