/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param name Name of the network.
 * @param id ID that uniquely identifies a network on a single machine.
 * @param created Date and time at which the network was created in [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format with nano-seconds.
 * @param scope The level at which the network exists (e.g. `swarm` for cluster-wide or `local` for machine level)
 * @param driver The name of the driver used to create the network (e.g. `bridge`, `overlay`).
 * @param enableIPv4 Whether the network was created with IPv4 enabled.
 * @param enableIPv6 Whether the network was created with IPv6 enabled.
 * @param IPAM
 * @param `internal` Whether the network is created to only allow internal networking connectivity.
 * @param attachable Whether a global / swarm scope network is manually attachable by regular containers from workers in swarm mode.
 * @param ingress Whether the network is providing the routing-mesh for the swarm cluster.
 * @param configFrom
 * @param configOnly Whether the network is a config-only network. Config-only networks are placeholder networks for network configurations to be used by other networks. Config-only networks cannot be used directly to run containers or services.
 * @param options Network-specific options uses when creating the network.
 * @param labels Metadata specific to the network being created.
 * @param peers List of peer nodes for an overlay network. This field is only present for overlay networks, and omitted for other network types.
 * @param containers Contains endpoints attached to the network.
 * @param services List of services using the network. This field is only present for swarm scope networks, and omitted for local scope networks.
 * @param status
 */
@JsonClass(generateAdapter = true)
data class NetworkInspect(
    // Name of the network.
    @Json(name = "Name")
    var name: kotlin.String? = null,
    // ID that uniquely identifies a network on a single machine.
    @Json(name = "Id")
    var id: kotlin.String? = null,
    // Date and time at which the network was created in [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format with nano-seconds.
    @Json(name = "Created")
    var created: kotlin.String? = null,
    // The level at which the network exists (e.g. `swarm` for cluster-wide or `local` for machine level)
    @Json(name = "Scope")
    var scope: kotlin.String? = null,
    // The name of the driver used to create the network (e.g. `bridge`, `overlay`).
    @Json(name = "Driver")
    var driver: kotlin.String? = null,
    // Whether the network was created with IPv4 enabled.
    @Json(name = "EnableIPv4")
    var enableIPv4: kotlin.Boolean? = null,
    // Whether the network was created with IPv6 enabled.
    @Json(name = "EnableIPv6")
    var enableIPv6: kotlin.Boolean? = null,
    @Json(name = "IPAM")
    var IPAM: IPAM? = null,
    // Whether the network is created to only allow internal networking connectivity.
    @Json(name = "Internal")
    var `internal`: kotlin.Boolean? = false,
    // Whether a global / swarm scope network is manually attachable by regular containers from workers in swarm mode.
    @Json(name = "Attachable")
    var attachable: kotlin.Boolean? = false,
    // Whether the network is providing the routing-mesh for the swarm cluster.
    @Json(name = "Ingress")
    var ingress: kotlin.Boolean? = false,
    @Json(name = "ConfigFrom")
    var configFrom: ConfigReference? = null,
    // Whether the network is a config-only network. Config-only networks are placeholder networks for network configurations to be used by other networks. Config-only networks cannot be used directly to run containers or services.
    @Json(name = "ConfigOnly")
    var configOnly: kotlin.Boolean? = false,
    // Network-specific options uses when creating the network.
    @Json(name = "Options")
    var options: kotlin.collections.MutableMap<kotlin.String, kotlin.String>? = null,
    // Metadata specific to the network being created.
    @Json(name = "Labels")
    var labels: kotlin.collections.MutableMap<kotlin.String, kotlin.String>? = null,
    // List of peer nodes for an overlay network. This field is only present for overlay networks, and omitted for other network types.
    @Json(name = "Peers")
    var peers: kotlin.collections.MutableList<PeerInfo>? = null,
    // Contains endpoints attached to the network.
    @Json(name = "Containers")
    var containers: kotlin.collections.MutableMap<kotlin.String, EndpointResource>? = null,
    // List of services using the network. This field is only present for swarm scope networks, and omitted for local scope networks.
    @Json(name = "Services")
    var services: kotlin.collections.MutableMap<kotlin.String, kotlin.Any>? = null,
    @Json(name = "Status")
    var status: NetworkStatus? = null,
)
