/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param name The network's name.
 * @param driver Name of the network driver plugin to use.
 * @param scope The level at which the network exists (e.g. `swarm` for cluster-wide or `local` for machine level).
 * @param `internal` Restrict external access to the network.
 * @param attachable Globally scoped network is manually attachable by regular containers from workers in swarm mode.
 * @param ingress Ingress network is the network which provides the routing-mesh in swarm mode.
 * @param configOnly Creates a config-only network. Config-only networks are placeholder networks for network configurations to be used by other networks. Config-only networks cannot be used directly to run containers or services.
 * @param configFrom
 * @param IPAM
 * @param enableIPv4 Enable IPv4 on the network.
 * @param enableIPv6 Enable IPv6 on the network.
 * @param options Network specific options to be used by the drivers.
 * @param labels User-defined key/value metadata.
 */
@JsonClass(generateAdapter = true)
data class NetworkCreateRequest(
    // The network's name.
    @Json(name = "Name")
    var name: kotlin.String,
    // Name of the network driver plugin to use.
    @Json(name = "Driver")
    var driver: kotlin.String? = "bridge",
    // The level at which the network exists (e.g. `swarm` for cluster-wide or `local` for machine level).
    @Json(name = "Scope")
    var scope: kotlin.String? = null,
    // Restrict external access to the network.
    @Json(name = "Internal")
    var `internal`: kotlin.Boolean? = null,
    // Globally scoped network is manually attachable by regular containers from workers in swarm mode.
    @Json(name = "Attachable")
    var attachable: kotlin.Boolean? = null,
    // Ingress network is the network which provides the routing-mesh in swarm mode.
    @Json(name = "Ingress")
    var ingress: kotlin.Boolean? = null,
    // Creates a config-only network. Config-only networks are placeholder networks for network configurations to be used by other networks. Config-only networks cannot be used directly to run containers or services.
    @Json(name = "ConfigOnly")
    var configOnly: kotlin.Boolean? = false,
    @Json(name = "ConfigFrom")
    var configFrom: ConfigReference? = null,
    @Json(name = "IPAM")
    var IPAM: IPAM? = null,
    // Enable IPv4 on the network.
    @Json(name = "EnableIPv4")
    var enableIPv4: kotlin.Boolean? = null,
    // Enable IPv6 on the network.
    @Json(name = "EnableIPv6")
    var enableIPv6: kotlin.Boolean? = null,
    // Network specific options to be used by the drivers.
    @Json(name = "Options")
    var options: kotlin.collections.MutableMap<kotlin.String, kotlin.String>? = null,
    // User-defined key/value metadata.
    @Json(name = "Labels")
    var labels: kotlin.collections.MutableMap<kotlin.String, kotlin.String>? = null,
)
