/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A descriptor struct containing digest, media type, and size, as defined in the [OCI Content Descriptors Specification](https://github.com/opencontainers/image-spec/blob/v1.0.1/descriptor.md).
 *
 * @param mediaType The media type of the object this schema refers to.
 * @param digest The digest of the targeted content.
 * @param propertySize The size in bytes of the blob.
 * @param urls List of URLs from which this object MAY be downloaded.
 * @param annotations Arbitrary metadata relating to the targeted content.
 * @param `data` Data is an embedding of the targeted content. This is encoded as a base64 string when marshalled to JSON (automatically, by encoding/json). If present, Data can be used directly to avoid fetching the targeted content.
 * @param platform
 * @param artifactType ArtifactType is the IANA media type of this artifact.
 */
@JsonClass(generateAdapter = true)
data class OCIDescriptor(
    // The media type of the object this schema refers to.
    @Json(name = "mediaType")
    var mediaType: kotlin.String? = null,
    // The digest of the targeted content.
    @Json(name = "digest")
    var digest: kotlin.String? = null,
    // The size in bytes of the blob.
    @Json(name = "size")
    var propertySize: kotlin.Long? = null,
    // List of URLs from which this object MAY be downloaded.
    @Json(name = "urls")
    var urls: kotlin.collections.MutableList<java.net.URI>? = null,
    // Arbitrary metadata relating to the targeted content.
    @Json(name = "annotations")
    var annotations: kotlin.collections.MutableMap<kotlin.String, kotlin.String>? = null,
    // Data is an embedding of the targeted content. This is encoded as a base64 string when marshalled to JSON (automatically, by encoding/json). If present, Data can be used directly to avoid fetching the targeted content.
    @Json(name = "data")
    var `data`: kotlin.String? = null,
    @Json(name = "platform")
    var platform: OCIPlatform? = null,
    // ArtifactType is the IANA media type of this artifact.
    @Json(name = "artifactType")
    var artifactType: kotlin.String? = null,
)
