/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param errorDetail
 * @param status
 * @param progressDetail
 */
@JsonClass(generateAdapter = true)
data class PushImageInfo(
    @Json(name = "errorDetail")
    var errorDetail: ErrorDetail? = null,
    @Json(name = "status")
    var status: kotlin.String? = null,
    @Json(name = "progressDetail")
    var progressDetail: ProgressDetail? = null,
)
