/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Information about the storage used for the container's root filesystem.
 *
 * @param snapshot
 */
@JsonClass(generateAdapter = true)
data class RootFSStorage(
    @Json(name = "Snapshot")
    var snapshot: RootFSStorageSnapshot? = null,
)
