/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Information about a snapshot backend of the container's root filesystem.
 *
 * @param name Name of the snapshotter.
 */
@JsonClass(generateAdapter = true)
data class RootFSStorageSnapshot(
    // Name of the snapshotter.
    @Json(name = "Name")
    var name: kotlin.String? = null,
)
