/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import de.gesellix.docker.remote.api.NetworkTaskInfo

/**
 * represents service parameters with the list of service's tasks
 *
 * @param VIP
 * @param ports
 * @param localLBIndex
 * @param tasks
 */
@JsonClass(generateAdapter = true)
data class ServiceInfo(
    @Json(name = "VIP")
    var VIP: kotlin.String? = null,
    @Json(name = "Ports")
    var ports: kotlin.collections.MutableList<kotlin.String>? = null,
    @Json(name = "LocalLBIndex")
    var localLBIndex: kotlin.Int? = null,
    @Json(name = "Tasks")
    var tasks: kotlin.collections.MutableList<NetworkTaskInfo>? = null,
)
