/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Dispatcher configuration.
 *
 * @param heartbeatPeriod The delay for an agent to send a heartbeat to the dispatcher.
 */
@JsonClass(generateAdapter = true)
data class SwarmSpecDispatcher(
    // The delay for an agent to send a heartbeat to the dispatcher.
    @Json(name = "HeartbeatPeriod")
    var heartbeatPeriod: kotlin.Long? = null,
)
