/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param imagesDiskUsage
 * @param containersDiskUsage
 * @param volumesDiskUsage
 * @param buildCacheDiskUsage
 */
@JsonClass(generateAdapter = true)
data class SystemDataUsageResponse(
    @Json(name = "ImagesDiskUsage")
    var imagesDiskUsage: ImagesDiskUsage? = null,
    @Json(name = "ContainersDiskUsage")
    var containersDiskUsage: ContainersDiskUsage? = null,
    @Json(name = "VolumesDiskUsage")
    var volumesDiskUsage: VolumesDiskUsage? = null,
    @Json(name = "BuildCacheDiskUsage")
    var buildCacheDiskUsage: BuildCacheDiskUsage? = null,
)
