/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package de.gesellix.docker.remote.api

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Options for configuring seccomp on the container
 *
 * @param mode
 * @param profile The custom seccomp profile as a json object
 */
@JsonClass(generateAdapter = true)
data class TaskSpecContainerSpecPrivilegesSeccomp(
    @Json(name = "Mode")
    var mode: TaskSpecContainerSpecPrivilegesSeccomp.Mode? = null,
    // The custom seccomp profile as a json object
    @Json(name = "Profile")
    var profile: kotlin.String? = null,
) {
    /**
     *
     *
     * Values: Default,Unconfined,Custom
     */
    @JsonClass(generateAdapter = false)
    enum class Mode(val value: kotlin.String) {
        @Json(name = "default")
        Default("default"),

        @Json(name = "unconfined")
        Unconfined("unconfined"),

        @Json(name = "custom")
        Custom("custom"),
    }
}
