---
name: CI
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
jobs:
  event-file:
    # https://github.com/marketplace/actions/publish-test-results#support-fork-repositories-and-dependabot-branches
    name: "Event File"
    runs-on: ubuntu-latest
    steps:
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: event-file
          path: ${{ github.event_path }}
  ci-build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        java:
          - 8
          - 17
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Set up JDK
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      # checks if updating the generated sources would succeed
      - name: clean updateApiModelSources
        run: ./gradlew clean updateApiModelSources --no-daemon --info --stacktrace
      - name: clean openApiGenerateCleanupGeneratedCode
        run: ./gradlew clean openApiGenerateCleanupGeneratedCode --no-daemon --info --stacktrace
      - name: clean ktlintFormat
        run: ./gradlew clean ktlintFormat --no-daemon --info --stacktrace
      - name: clean build
        run: ./gradlew clean build --no-daemon --info --stacktrace
      - name: Upload Test Results
        # see publish-test-results.yml for workflow that publishes test results without security issues for forks
        # https://github.com/marketplace/actions/publish-test-results#support-fork-repositories-and-dependabot-branches
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Test Results (Java ${{ matrix.java }} on ${{ matrix.os }})
          path: '**/build/test-results/test/TEST-*.xml'
...
