inputSpec: https://docs.docker.com/engine/api/v1.41.yaml
additionalProperties:
  hideGenerationTimestamp: true
generatorName: kotlin
packageName: de.gesellix.docker.remote.api
invokerPackage: de.gesellix.docker.remote.invoker
apiPackage: de.gesellix.docker.remote.client.api
modelPackage: de.gesellix.docker.remote.api
enumPropertyNaming: PascalCase
groupId: de.gesellix
artifactId: docker-remote-api-model
artifactVersion: 1.41
outputDir: api-model-v1-41
dateLibrary: java8
moshiCodeGen: true
